import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Monopoly ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body className="h-full w-full antialiased" 
      style = 
      {{
        backgroundImage: "url('/slogan-modals/bdd319feedf8fd013280e88055896619 2 (1).png')",
        backgroundPosition: 'center center',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'cover',
        overflow:"hidden"
      }}
      >
        {children}
      </body>
    </html>
  );
}

